package igu;

import static igu.Administracion.modeloCourse;
import javax.swing.JOptionPane;
import proyecto1courses.Controladora;
import static proyecto1courses.Controladora.cursosArray;
import static proyecto1courses.Controladora.profesoresArray;
import proyecto1courses.Course;
import proyecto1courses.Professor;


public class AddCourse extends javax.swing.JFrame {

   Controladora control = new Controladora();
    public AddCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodeCourse = new javax.swing.JTextField();
        txtNameCourse = new javax.swing.JTextField();
        txtCreditCourse = new javax.swing.JTextField();
        btnAddCourse = new javax.swing.JButton();
        cmbProfesor = new javax.swing.JComboBox<>();
        btnShowProf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 28, 48));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agregar nuevo curso");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Código:");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Creditos:");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Profesor:");

        txtCodeCourse.setBackground(new java.awt.Color(255, 255, 255));
        txtCodeCourse.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtCodeCourse.setForeground(new java.awt.Color(0, 0, 0));
        txtCodeCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeCourseActionPerformed(evt);
            }
        });

        txtNameCourse.setBackground(new java.awt.Color(255, 255, 255));
        txtNameCourse.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtNameCourse.setForeground(new java.awt.Color(0, 0, 0));
        txtNameCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameCourseActionPerformed(evt);
            }
        });

        txtCreditCourse.setBackground(new java.awt.Color(255, 255, 255));
        txtCreditCourse.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtCreditCourse.setForeground(new java.awt.Color(0, 0, 0));
        txtCreditCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditCourseActionPerformed(evt);
            }
        });

        btnAddCourse.setText("Agregar");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        btnShowProf.setText("Update");
        btnShowProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txtCodeCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameCourse)
                            .addComponent(txtCreditCourse)
                            .addComponent(cmbProfesor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowProf)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodeCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNameCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCreditCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowProf))
                .addGap(18, 18, 18)
                .addComponent(btnAddCourse)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeCourseActionPerformed

    private void txtNameCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameCourseActionPerformed

    private void txtCreditCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditCourseActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        // TODO add your handling code here:
       
        
        try {
            String code = txtCodeCourse.getText();
            String name = txtNameCourse.getText();
            int credit = Integer.valueOf(txtCreditCourse.getText());
            
            int indexProfesor = cmbProfesor.getSelectedIndex();
            
            Professor profesor = profesoresArray.get(indexProfesor);
            
            control.addCourse(code, name, credit, profesor);
            
            refreshTable();
            dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al agregar Curso");
        }
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnShowProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowProfActionPerformed
        // TODO add your handling code here:
        
        for(Professor profesor: profesoresArray){
            cmbProfesor.addItem(profesor.getName() + " " +profesor.getLastName());
        }
        
    }//GEN-LAST:event_btnShowProfActionPerformed

    
    public void refreshTable(){
        while (modeloCourse.getRowCount() > 0) { 
            modeloCourse.removeRow(0);
        }
        
        for (Course curso: cursosArray) {
            if (curso != null) {
                Object a[]= new Object[5];
                a[0] = curso.getCodeCourse();
                a[1] = curso.getNameCourse();
                a[2] = curso.getCredits();
                a[3] = curso.getStudentsArray().size();
                a[4] = curso.getProfesor().getName() + " " + curso.getProfesor().getLastName();

                modeloCourse.addRow(a);
            }
        }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnShowProf;
    private javax.swing.JComboBox<String> cmbProfesor;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodeCourse;
    private javax.swing.JTextField txtCreditCourse;
    private javax.swing.JTextField txtNameCourse;
    // End of variables declaration//GEN-END:variables
}
