
package igu;

import static igu.LogIn.profesorLogged;
import javax.swing.JButton;
import proyecto1courses.Course;


public class MenuProfesor extends javax.swing.JFrame {

    
    public MenuProfesor() {
        initComponents();
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnUpdateProfesor = new javax.swing.JButton();
        labelSaludar = new javax.swing.JLabel();
        btnCourse1 = new javax.swing.JButton();
        txtCantStudent1 = new javax.swing.JTextField();
        btnCourse2 = new javax.swing.JButton();
        txtCantStudent2 = new javax.swing.JTextField();
        btnCourse3 = new javax.swing.JButton();
        txtCantStudent3 = new javax.swing.JTextField();
        btnCourse4 = new javax.swing.JButton();
        txtCantStudent4 = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        cboCursosDeProfesor = new javax.swing.JComboBox<>();
        btnGoToCourse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(23, 107, 135));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cursos Asignados");

        btnUpdateProfesor.setBackground(new java.awt.Color(0, 28, 48));
        btnUpdateProfesor.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateProfesor.setText("Actualizar Datos");
        btnUpdateProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfesorActionPerformed(evt);
            }
        });

        labelSaludar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labelSaludar.setForeground(new java.awt.Color(255, 255, 255));
        labelSaludar.setText("insertar nombre profesor");

        btnCourse1.setBackground(new java.awt.Color(0, 28, 48));
        btnCourse1.setForeground(new java.awt.Color(255, 255, 255));
        btnCourse1.setText("Curso 1");
        btnCourse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourse1ActionPerformed(evt);
            }
        });

        txtCantStudent1.setBackground(new java.awt.Color(100, 204, 197));
        txtCantStudent1.setForeground(new java.awt.Color(0, 0, 0));
        txtCantStudent1.setText("Cant. Students");
        txtCantStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantStudent1ActionPerformed(evt);
            }
        });

        btnCourse2.setBackground(new java.awt.Color(0, 28, 48));
        btnCourse2.setForeground(new java.awt.Color(255, 255, 255));
        btnCourse2.setText("Curso 2");

        txtCantStudent2.setBackground(new java.awt.Color(100, 204, 197));
        txtCantStudent2.setForeground(new java.awt.Color(0, 0, 0));
        txtCantStudent2.setText("Cant. Students");
        txtCantStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantStudent2ActionPerformed(evt);
            }
        });

        btnCourse3.setBackground(new java.awt.Color(0, 28, 48));
        btnCourse3.setForeground(new java.awt.Color(255, 255, 255));
        btnCourse3.setText("Curso 3");

        txtCantStudent3.setBackground(new java.awt.Color(100, 204, 197));
        txtCantStudent3.setForeground(new java.awt.Color(0, 0, 0));
        txtCantStudent3.setText("Cant. Students");
        txtCantStudent3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantStudent3ActionPerformed(evt);
            }
        });

        btnCourse4.setBackground(new java.awt.Color(0, 28, 48));
        btnCourse4.setForeground(new java.awt.Color(255, 255, 255));
        btnCourse4.setText("Curso 4");

        txtCantStudent4.setBackground(new java.awt.Color(100, 204, 197));
        txtCantStudent4.setForeground(new java.awt.Color(0, 0, 0));
        txtCantStudent4.setText("Cant. Students");
        txtCantStudent4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantStudent4ActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(23, 107, 135));
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refrescar");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(23, 107, 135));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        cboCursosDeProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGoToCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnGoToCourse.setText("Ir a Curso");
        btnGoToCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdateProfesor))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCantStudent3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCourse3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCantStudent1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(btnCourse1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCantStudent2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCourse2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCantStudent4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCourse4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(80, 80, 80))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelSaludar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(cboCursosDeProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGoToCourse)
                                .addGap(185, 185, 185))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(btnUpdateProfesor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelSaludar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCourse3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantStudent3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCourse4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantStudent4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cboCursosDeProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGoToCourse)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantStudent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantStudent1ActionPerformed

    private void txtCantStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantStudent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantStudent2ActionPerformed

    private void txtCantStudent3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantStudent3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantStudent3ActionPerformed

    private void txtCantStudent4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantStudent4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantStudent4ActionPerformed

    private void btnCourse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourse1ActionPerformed
        // TODO add your handling code here:
        AdministracionCurso adminCursoWindow = new AdministracionCurso();
        
        adminCursoWindow.setVisible(true);
        adminCursoWindow.setLocationRelativeTo(null);
      
    }//GEN-LAST:event_btnCourse1ActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        btnCourse1.setText(profesorLogged.getCursosProfArray().get(0).getNameCourse());
        txtCantStudent1.setText(String.valueOf(profesorLogged.getCursosProfArray().get(0).getStudentsArray().size()));
        for(Course curso: profesorLogged.getCursosProfArray()){
            cboCursosDeProfesor.addItem(curso.getNameCourse());
        }
        
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnUpdateProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfesorActionPerformed
        // TODO add your handling code here:
        UpdateProfessorLogged updateThisProfessor = new UpdateProfessorLogged();
        updateThisProfessor.setVisible(true);
        updateThisProfessor.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnUpdateProfesorActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
        LogIn logInWindow = new LogIn();
        logInWindow.setVisible(true);
        logInWindow.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnGoToCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToCourseActionPerformed
        // TODO add your handling code here:
        AdministracionCurso adminCursoWindow = new AdministracionCurso();
        
        adminCursoWindow.setVisible(true);
        adminCursoWindow.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnGoToCourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourse1;
    private javax.swing.JButton btnCourse2;
    private javax.swing.JButton btnCourse3;
    private javax.swing.JButton btnCourse4;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGoToCourse;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdateProfesor;
    private javax.swing.JComboBox<String> cboCursosDeProfesor;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel labelSaludar;
    private javax.swing.JTextField txtCantStudent1;
    private javax.swing.JTextField txtCantStudent2;
    private javax.swing.JTextField txtCantStudent3;
    private javax.swing.JTextField txtCantStudent4;
    // End of variables declaration//GEN-END:variables
}
